export const PROJECTS_LİST = [
  {
    pName: 'ATB',
    use: ['NextJS', 'TailwindCSS', 'Firebase'],
    siteURL: 'https://armaturkbirlikleri.vercel.app/',
    github: 'https://github.com/Elitesmert/atb',
    desc: 'A project I made for my friends. A site where the group is promoted and applications are received. It is actively used.',
    imageSRC: '/armaturkbirlikleri.png',
    idev: false,
  },
  {
    pName: 'Petbook',
    use: ['Vite', 'TailwindCSS'],
    siteURL: 'https://petbookapp.vercel.app/',
    github: 'https://github.com/Elitesmert/Petbook-v1.0',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies ultrices, nunc nisl ultricies nunc, vitae',
    imageSRC: '/petbookapp.png',
    idev: true,
  },
  {
    pName: 'Weather App',
    use: ['Vite', 'TailwindCSS', 'NextUi', 'Axios'],
    siteURL: 'https://weather-app-first.vercel.app/',
    github: 'https://github.com/Elitesmert/weather-app',
    desc: 'I made a weather application that can draw api with axios.',
    imageSRC: '/weatherapp.png',
    idev: false,
  },
  {
    pName: 'Shop App',
    use: ['Vite', 'TailwindCSS', 'Supabase', 'Strapi', 'Redux', 'Axios','Sass'],
    siteURL: 'https://clothsstore.vercel.app/',
    github: 'https://github.com/Elitesmert/Shop-App',
    desc: "It's a small shop app I made using Strapi and Supabase. Not responsive.",
    imageSRC: '/shopapp.png',
    idev: false,
  },
]
