export const PROJECTS_LİST = [
  {
    pName: 'First MERN Project',
    use: ['MongoDB', 'Express', 'ReactJS', 'NodeJS'],
    siteURL: 'https://first-mern-pnqs.onrender.com',
    github: 'https://github.com/Elitesmert/First-MERN',
    desc: 'My first MERN project. I made a simple real estate site. An application I made to learn backend. This website is published on render.com so it may take a while to open.',
    imageSRC: '/firstmern.png',
    idev: false,
  },
  {
    pName: 'Shop App',
    use: ['TailwindCSS', 'Supabase', 'Strapi', 'Redux', 'Axios', 'Sass'],
    siteURL: 'https://clothsstore.vercel.app/',
    github: 'https://github.com/Elitesmert/Shop-App',
    desc: "It's a small shop app I made using Strapi and Supabase. Not responsive.",
    imageSRC: '/shopapp.png',
    idev: false,
  },
  {
    pName: 'Entertainment Web App',
    use: ['React', 'TailwindCSS', 'NextUi'],
    siteURL: 'https://entertainment-web-appp.vercel.app/',
    github: 'https://github.com/Elitesmert/entertainment-web-app',
    desc: 'A web application I made to do some filtering more smoothly. I used NextUi for some TailwindCSS configurations. Design by frontendmentor.io.',
    imageSRC: '/entertainmentapp.png',
    idev: false,
  },
  {
    pName: 'Space Tourism Website (24h Challenge)',
    use: ['React', 'TailwindCSS', 'NextUi'],
    siteURL: 'https://space-tourism-website.vercel.app/',
    github: 'https://github.com/Elitesmert/space-tourism-website',
    desc: "This website is an outcome of a 24 hour challenge. I'm using NextUi for some Tailwind CSS configurations. Designed by Frontendmentor.io",
    imageSRC: '/spacetourism.png',
    idev: false,
  },
  {
    pName: 'Petbook',
    use: ['Vite', 'TailwindCSS'],
    siteURL: 'https://petbookapp.vercel.app/',
    github: 'https://github.com/Elitesmert/Petbook-v1.0',
    desc: '',
    imageSRC: '/petbookapp.png',
    idev: true,
  },
  {
    pName: 'Weather App',
    use: ['Vite', 'TailwindCSS', 'NextUi', 'Axios'],
    siteURL: 'https://weather-app-first.vercel.app/',
    github: 'https://github.com/Elitesmert/weather-app',
    desc: 'I made a weather application that can draw api with axios.',
    imageSRC: '/weatherapp.png',
    idev: false,
  },
  {
    pName: 'ATB',
    use: ['NextJS', 'TailwindCSS', 'Firebase'],
    siteURL: 'https://armaturkbirlikleri.vercel.app/',
    github: 'https://github.com/Elitesmert/atb',
    desc: 'A project I made for my friends. A site where the group is promoted and applications are received. It is actively used.',
    imageSRC: '/armaturkbirlikleri.png',
    idev: false,
  },
]
